import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
  <nav style={{
    backgroundColor: '#222',
    padding: '1rem',
    display: 'flex',
    gap: '1rem',
  }}>
    <a href="/" style={{ color: '#fff', textDecoration: 'none' }}>Home</a>
    <a href="/about" style={{ color: '#fff', textDecoration: 'none' }}>About</a>
    <a href="/privacy" style={{ color: '#fff', textDecoration: 'none' }}>Privacy</a>
    <a href="/terms" style={{ color: '#fff', textDecoration: 'none' }}>Terms</a>
    <a href="/disclaimer" style={{ color: '#fff', textDecoration: 'none' }}>Disclaimer</a>
  </nav>
  {children}
      </body>
    </html>
  );
}
