import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TermsModal from '../components/TermsModal';
import Link from 'next/link';

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <TermsModal />
  <nav style={{
    backgroundColor: '#222',
    padding: '1rem',
    display: 'flex',
    gap: '1rem',
  }}>
    <nav>
  <Link href="/">Home     </Link>
  <Link href="/about">About     </Link>
  <Link href="/privacy">Privacy     </Link>
  <Link href="/terms">Terms     </Link>
  <Link href="/disclaimer">Disclaimer     </Link>
</nav>

  </nav>
  {children}
      </body>
    </html>
  );
}
